data_info:
  root_path: ""  # Data root path 
  csv_root_path: "/av_deepfake_1m/av_deepfake_1m/"  # Path to the folder containing split csv's
  metadata_path: "/av_deepfake_1m/av_deepfake_1m/val_metadata.json"
  fvfa_rvra_only: True
  apply_l2: True  # Apply l2 normalization of input features (always used in our experiments)
  input_type: "both"  # both, video, audio (choose either to use both modalities or just one of them)

ckpt_path: ""  # Path to the model ckpt

output_path: ""  # Path to output folder

seed: 43